export const NAV_ADD_NOTE = 'NAV_ADD_NOTE';
export const NAV_EDIT_NOTE = 'NAV_EDIT_NOTE';

export const NOTES_AVAILABLE = 'NOTES_AVAILABLE';
export const ADD_NOTE = 'ADD_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const ARCHIVES_AVAILABLE = 'ARCHIVES_AVAILABLE';
export const ADD_ARCHIVE = 'ADD_ARCHIVE';
export const UPDATE_ARCHIVE = 'UPDATE_ARCHIVE';
export const DELETE_ARCHIVE = 'DELETE_ARCHIVE';

export const ADD_TRASH = 'ADD_TRASH';
export const TRASH_AVAILABLE = 'TRASH_AVAILABLE';
export const DELETE_TRASH = 'DELETE_TRASH';

export const MARKERS_AVAILABLE = 'MARKERS_AVAILABLE';
export const UPDATE_MARKERS = 'UPDATE_MARKERS';

export const SET_MARKER_KEY = 'SET_MARKER_KEY';
